DATASET:
  TRAIN:
    TYPE: 'dme'
    ROOT: './data/dme/'
    ANN: 'label/train.json'
    AUG:
      FLIP: false
      SCALE: false
      SCALE_FACTOR: 0.3
  VAL:
    TYPE: 'dme'
    ROOT: './data/dme/'
    ANN: 'label/train.json'
  TEST:
    TYPE: 'dme'
    ROOT: './data/dme/'
    ANN: 'label/test.json'
DATA_PRESET:
  NORM_TYPE: 'gumbel_softmax'
  GUMBEL:
    TAU: 5
    NUM_ITER: 30
    INDX_SAMPLE: 'gaussian'
  IMAGE_SIZE:
  - 224
  - 768
  NUM_SURFACE: 8
  LOSS: 'ce'
  LOSS_ALPHA: 0
TRAIN:
  BATCH_SIZE: 2
  BEGIN_EPOCH: 0
  END_EPOCH: 200
  OPTIMIZER: 'adam'
  LR: 0.0001
  LR_WEIGHT_DECAY: 0.0001
  LR_FACTOR: 0.1
  LR_STEP:
  - 150
  - 200