DATASET:
  TRAIN:
    TYPE: 'hc'
    ROOT: './data/hc/'
    ANN: 'label/train.json'
    AUG:
      FLIP: true
      SCALE: false
      SCALE_FACTOR: 0.3
  VAL:
    TYPE: 'hc'
    ROOT: './data/hc/'
    ANN: 'label/valid.json'
  TEST:
    TYPE: 'hc'
    ROOT: './data/hc/'
    ANN: 'label/test.json'
DATA_PRESET:
  NORM_TYPE: 'gumbel_softmax'
  GUMBEL:
    TAU: 2
    NUM_ITER: 30
  IMAGE_SIZE:
  - 128
  - 1024
  NUM_SURFACE: 9
TRAIN:
  BATCH_SIZE: 2
  BEGIN_EPOCH: 0
  END_EPOCH: 40
  OPTIMIZER: 'adam'
  LR: 0.0001
  LR_WEIGHT_DECAY: 0.0001
  LR_FACTOR: 0.1
  LR_STEP:
  - 10
  - 40