DATASET:
  TRAIN:
    TYPE: 'hc'
    ROOT: './data/hc/'
    ANN: 'label/train.json'
    AUG:
      FLIP: true
      ROT_FACTOR: 40
      SCALE_FACTOR: 0.3
      NUM_JOINTS_HALF_BODY: 8
      PROB_HALF_BODY: -1
  VAL:
    TYPE: 'hc'
    ROOT: './data/hc/'
    ANN: 'label/valid.json'
  TEST:
    TYPE: 'hc'
    ROOT: './data/hc/'
    ANN: 'label/test.json'
DATA_PRESET:
  NORM_TYPE: 'softmax'
  IMAGE_SIZE:
  - 128
  - 1024
  NUM_SURFACE: 9
TRAIN:
  BATCH_SIZE: 2
  BEGIN_EPOCH: 0
  END_EPOCH: 15
  OPTIMIZER: 'adam'
  LR: 0.0001
  LR_WEIGHT_DECAY: 0.0001
  LR_FACTOR: 0.1
  LR_STEP:
  - 5
  - 10
VAL:
  CLIMS:
  - 0
  - 1023