DATASET:
  TRAIN:
    TYPE: 'hc'
    ROOT: './data/hc/'
    ANN: 'labels/train.json'
    AUG:
      FLIP: true
      ROT_FACTOR: 40
      SCALE_FACTOR: 0.3
      NUM_JOINTS_HALF_BODY: 8
      PROB_HALF_BODY: -1
  VAL:
    TYPE: 'hc'
    ROOT: './data/hc/'
    ANN: 'labels/valid.json'
  TEST:
    TYPE: 'hc'
    ROOT: './data/coco/'
    ANN: 'labels/test.json'
DATA_PRESET:
  NORM_TYPE: 'softmax'
  IMAGE_SIZE:
  - 496
  - 768
TRAIN:
  BATCH_SIZE: 32
  BEGIN_EPOCH: 0
  END_EPOCH: 200
  OPTIMIZER: 'adam'
  LR: 0.001
  LR_FACTOR: 0.1
  LR_STEP:
  - 90
  - 120